version: '3'

networks:
  1panel-network:
    external: true

services:
  paseo:
    image: ghcr.io/ifty-r/paseo-docker:latest
    container_name: paseo
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-6767}:6767"
    environment:
      PASEO_PASSWORD: "${PASEO_PASSWORD:-3561374993}"
      # PASEO_HOSTNAMES: "paseo.example.com"
    volumes:
      - ./paseo-home:/home/paseo
      - ./workspace:/workspace
    networks:
      - 1panel-network
