networks:
  1panel-network:
    external: true

services:
  paseo:
    image: ghcr.io/ifty-r/paseo-docker:latest
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-6767}:6767"
    environment:
      PASEO_PASSWORD: "${PASEO_PASSWORD:-3561374993}"
      AUTO_UPDATE_AGENT_CLIS: "${AUTO_UPDATE_AGENT_CLIS:-true}"
      AUTO_UPDATE_AGENT_CLIS_BACKGROUND: "${AUTO_UPDATE_AGENT_CLIS_BACKGROUND:-true}"
      AGENT_CLI_UPDATE_INTERVAL_HOURS: "${AGENT_CLI_UPDATE_INTERVAL_HOURS:-72}"
      AGENT_CLI_UPDATE_CHECK_INTERVAL_SECONDS: "${AGENT_CLI_UPDATE_CHECK_INTERVAL_SECONDS:-3600}"
      # PASEO_HOSTNAMES: "paseo.example.com"
    volumes:
      - ./paseo-home:/home/paseo
      - ./workspace:/workspace
    networks:
      - 1panel-network
